import fs from 'fs';
import path from 'path';

// Read JSON generated by powershell or do it here
// Since we have signatures from task-233, we can just do it in JS
// Wait, we can reuse the signature-fetching logic in match_all.mjs but print top 5 for ALL files!
// Let's write a quick script that reads all files and outputs top 5 matches for the files in question.
// Actually, let's write it in match_all.mjs but save it as find_top_5.mjs.

import { execSync } from 'child_process';

function getImageProfile(filePath) {
  const psPath = filePath.replace(/\\/g, '\\\\');
  const psCommand = `
    Add-Type -AssemblyName System.Drawing;
    $img = [System.Drawing.Image]::FromFile('${psPath}');
    $bmp = New-Object System.Drawing.Bitmap($img);
    $width = $bmp.Width;
    $height = $bmp.Height;
    $gridSize = 5;
    $stepX = [math]::Floor($width / ($gridSize + 1));
    $stepY = [math]::Floor($height / ($gridSize + 1));
    $sig = @();
    for ($i = 1; $i -le $gridSize; $i++) {
        for ($j = 1; $j -le $gridSize; $j++) {
            $x = $i * $stepX;
            $y = $j * $stepY;
            if ($x -lt $width -and $y -lt $height) {
                $pixel = $bmp.GetPixel($x, $y);
                $sig += $pixel.R;
                $sig += $pixel.G;
                $sig += $pixel.B;
            }
        }
    };
    $img.Dispose();
    Write-Output ($sig -join ',');
  `;
  try {
    const cleanCmd = psCommand.replace(/\r?\n/g, ' ');
    const stdout = execSync(`powershell -NoProfile -Command "${cleanCmd}"`, { encoding: 'utf8' });
    return stdout.trim().split(',').map(Number);
  } catch (err) {
    return null;
  }
}

const mediaFiles = [
  "media__1781424169454.jpg",
  "media__1781425832811.jpg",
  "media__1781425832814.jpg",
  "media__1781425832816.jpg",
  "media__1781427468982.jpg"
];

const targetDir = 'public/galleries/דיוקן קןרונה ברישום ואקוורל/דיוקן קןרונה ברישום ואקוורל';
const originalFiles = fs.readdirSync(targetDir).filter(f => f.endsWith('.jpg') || f.endsWith('.JPG'));

const originalNames = originalFiles.map(f => {
  const bakFile = f + '.bak';
  if (fs.existsSync(path.join(targetDir, bakFile))) {
    return { name: f, scanFile: bakFile };
  }
  return { name: f, scanFile: f };
});

const mediaSigs = {};
mediaFiles.forEach(f => {
  mediaSigs[f] = getImageProfile(path.resolve('scratch', f));
});

const originalSigs = {};
originalNames.forEach(o => {
  originalSigs[o.name] = getImageProfile(path.resolve(targetDir, o.scanFile));
});

mediaFiles.forEach(m => {
  const mSig = mediaSigs[m];
  if (!mSig) return;
  
  console.log(`\nUploaded File: ${m}`);
  const results = [];
  
  Object.keys(originalSigs).forEach(oName => {
    const oSig = originalSigs[oName];
    if (mSig.length === oSig.length) {
      let sumSq = 0;
      for (let i = 0; i < mSig.length; i++) {
        const diff = mSig[i] - oSig[i];
        sumSq += diff * diff;
      }
      const dist = Math.sqrt(sumSq);
      results.push({ name: oName, distance: dist });
    }
  });
  
  results.sort((a, b) => a.distance - b.distance);
  results.slice(0, 5).forEach((r, idx) => {
    console.log(`  Match #${idx + 1}: ${r.name} -> Distance: ${r.distance.toFixed(2)}`);
  });
});
